export const countries = [
    { "code": "US", "name": "United States" },
    { "code": "CA", "name": "Canada" },
    { "code": "GB", "name": "United Kingdom" },
    { "code": "AU", "name": "Australia" },
    { "code": "DE", "name": "Germany" },
    { "code": "FR", "name": "France" },
    { "code": "JP", "name": "Japan" },
    { "code": "CN", "name": "China" },
    { "code": "IT", "name": "Italy" },
    { "code": "ES", "name": "Spain" },
    { "code": "RU", "name": "Russia" },
    { "code": "IN", "name": "India" },
    { "code": "BR", "name": "Brazil" },
    { "code": "SE", "name": "Sweden" },
    { "code": "NO", "name": "Norway" },
    { "code": "DK", "name": "Denmark" },
    { "code": "FI", "name": "Finland" },
    { "code": "NZ", "name": "New Zealand" },
    { "code": "MX", "name": "Mexico" },
    { "code": "ZA", "name": "South Africa" },
    { "code": "EG", "name": "Egypt" },
    { "code": "NG", "name": "Nigeria" },
    { "code": "KE", "name": "Kenya" },
    { "code": "UA", "name": "Ukraine" },
    { "code": "SA", "name": "Saudi Arabia" },
    { "code": "AE", "name": "United Arab Emirates" },
    { "code": "TR", "name": "Turkey" },
    { "code": "SG", "name": "Singapore" },
    { "code": "MY", "name": "Malaysia" },
    { "code": "ID", "name": "Indonesia" },
    { "code": "PH", "name": "Philippines" },
    { "code": "TH", "name": "Thailand" },
    { "code": "KR", "name": "South Korea" },
    { "code": "VN", "name": "Vietnam" },
    { "code": "IR", "name": "Iran" },
    { "code": "PK", "name": "Pakistan" },
    { "code": "BD", "name": "Bangladesh" },
    { "code": "PL", "name": "Poland" },
    { "code": "NL", "name": "Netherlands" },
    { "code": "BE", "name": "Belgium" },
    { "code": "GR", "name": "Greece" },
    { "code": "CZ", "name": "Czech Republic" },
    { "code": "PT", "name": "Portugal" },
    { "code": "HU", "name": "Hungary" },
    { "code": "AT", "name": "Austria" },
    { "code": "CH", "name": "Switzerland" },
    { "code": "LU", "name": "Luxembourg" },
    { "code": "IE", "name": "Ireland" },
    { "code": "CO", "name": "Colombia" },
    { "code": "AR", "name": "Argentina" }
  ]
  